# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0006_auto_20161216_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coolapp.User'),
        ),
    ]
